"""Add oauth_provider to User model

Revision ID: 558ec347fb30
Revises: 69aaa8ba0f5c
Create Date: 2025-10-23 14:43:42.624645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558ec347fb30'
down_revision = '69aaa8ba0f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
